apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
  namespace: employee-management
spec:
  replicas: 2

  selector:
    matchLabels:
      app: employee-management

  template:
    metadata:
      labels:
        app: employee-management

    spec:
      containers:
        - name: employee-management

          image: employee-management-system:1.0.0

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: employee-management-config
                  key: SPRING_PROFILES_ACTIVE

            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: employee-management-config
                  key: SERVER_PORT

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
